### ISSUE TITLE
SonosBar : parse stdout 001-sonosBar.py:8 unknown parameter: Support/xbar/plugins/001-sonosBar.py param1

### ISSUE THREAD

**Issue by bigornoo** [anergictcell/SonosBar#1]
Hi, this plugin does not work. 
There is an error : 
parse stdout 001-sonosBar.py:8 unknown parameter: Support/xbar/plugins/001-sonosBar.py param1
Python 3.9 (macports)
macOS 11.6.1
Xbar 2.1.7-beta
The script works well in CLI.
Thank you for your help.

**Comment by anergictcell** [comment]
Hi,
Ui, I haven't touched the code here for 5 years, so it'll take some time to get to the bottom of it.
The error itself looks like something is wrongly configured in xbar, rather than the Python script. 
The `..unknown paramater: ... param1` looks like something from the xbar API.
I will have a look and try to reproduce the issue. What might help is to change the shebang of the python file and ensure it points at the right python interpreter.

**Comment by bigornoo** [comment]
Hi,
Changing the shebang did not solve the problem.

**Comment by anergictcell** [comment]
Hi,

I think I found the issue. Can you try using the `sonosBar.py` script from the root folder and see if that works? It it works, I'll make a pull request with `xbar` to have it available properly in the app.

There were two issues:

1. `xbar` couldn't properly handle the the path to the plugin folder if it contains spaces. I have now quoted the path
2. The function to get the local IP address didn't work with newer MacOs versions anymore. I've now changed this - at least it now works on my Mac :)

**Comment by bigornoo** [comment]
hi,
What root are you talking about ?

**Comment by anergictcell** [comment]
The root folder of this repository. Basically this file: https://github.com/anergictcell/SonosBar/blob/master/sonosBar.py

**Comment by bigornoo** [comment]
It's working now with the latest revision and a custom python path.
Thank you very much !
